### ISSUE TITLE
What's Wrong with this kind of error message?I have just use it last night,but today ,it is not working.

### ISSUE THREAD

**Issue by GuessWhoIAm-MyGithub** [Waldenth/FuckHamSports#1]
![image](https://user-images.githubusercontent.com/67901624/117565116-43b58880-b0e2-11eb-83f0-f422581a05f4.png)

**Comment by Waldenth** [comment]
Well,I guess your IMEI code may have expired,  the IMEI code will update about once a week.  I use a code about a month ago and the result is a repetition of yours . So my advice is use network packet capture tool to get your IMEI code again . If the new code is different , that's probably the problem

**Comment by GuessWhoIAm-MyGithub** [comment]
> Well,I guess your IMEI code may have expired, the IMEI code will update about once a week. I use a code about a month ago and the result is a repetition of yours . So my advice is use network packet capture tool to get your IMEI code again . If the new code is different , that's probably the problem

Will my account possibly be banned because of using this SoftWare？ (I will not change your parameters except latitude and longitude。)

**Comment by Waldenth** [comment]
> > Well,I guess your IMEI code may have expired, the IMEI code will update about once a week. I use a code about a month ago and the result is a repetition of yours . So my advice is use network packet capture tool to get your IMEI code again . If the new code is different , that's probably the problem
> 
> Will my account possibly be banned because of using this SoftWare？ (I will not change your parameters except latitude and longitude。)

Any more questions ? If you no longer need help, I will close this issue in the next few days.Again, sincerely thanks to your feedback.
