### ISSUE TITLE
emm

### ISSUE THREAD

**Issue by woniu9524** [Waldenth/FuckHamSports#2]
不用休眠，改一下时间可以直接跑
然后，能不能打包成exe，这样没有java环境的好打开

**Comment by Waldenth** [comment]
> 不用休眠，改一下时间可以直接跑
> 然后，能不能打包成exe，这样没有java环境的好打开

加休眠是出于对防止服务器端对Get请求的时间进行时钟检测（如果你的开始与结束跑步请求之间间隔的时间很短，而最后的结束请求携带的时间却有几百秒，这样运维方很容易查到异常），我无法保证这样做是否会对账号造成影响。
Java程序的运行必须依赖java环境，即使是exe。如果打包成exe必须在exe中包含jdk，考虑到jdk体积太大，没有进行打包。后续我考虑将其做成开放性Web平台或使用C#进行重构。

**Comment by woniu9524** [comment]
我试过很多次了，直接没问题。
然后你把jdk打进去吧……他们用的人安装个jdk确实太为难了。可以单独打包一个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Waldenth/FuckHamSports] emm (#2)





  
不用休眠，改一下时间可以直接跑
 然后，能不能打包成exe，这样没有java环境的好打开
  
加休眠是出于对防止服务器端对Get请求的时间进行时钟检测（如果你的开始与结束跑步请求之间间隔的时间很短，而最后的结束请求携带的时间却有几百秒，这样运维方很容易查到异常），我无法保证这样做是否会对账号造成影响。
 Java程序的运行必须依赖java环境，即使是exe。如果打包成exe必须在exe中包含jdk，考虑到jdk体积太大，没有进行打包。后续我考虑将其做成开放性Web平台或使用C#进行重构。

**Comment by Waldenth** [comment]
> 我试过很多次了，直接没问题。 然后你把jdk打进去吧……他们用的人安装个jdk确实太为难了。可以单独打包一个版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月16日(星期天) 下午2:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Waldenth/FuckHamSports] emm (#2) 不用休眠，改一下时间可以直接跑 然后，能不能打包成exe，这样没有java环境的好打开 加休眠是出于对防止服务器端对Get请求的时间进行时钟检测（如果你的开始与结束跑步请求之间间隔的时间很短，而最后的结束请求携带的时间却有几百秒，这样运维方很容易查到异常），我无法保证这样做是否会对账号造成影响。 Java程序的运行必须依赖java环境，即使是exe。如果打包成exe必须在exe中包含jdk，考虑到jdk体积太大，没有进行打包。后续我考虑将其做成开放性Web平台或使用C#进行重构。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢你的建议，我已经更新工程项目，现在可以自我选择是否进行延时模拟；同时，网盘中我更新了打包jre环境，无需安装JDK的项目，使用简单的bat/vbs/exe控制执行，你可以实验一下。

**Comment by woniu9524** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Waldenth/FuckHamSports] emm (#2)





  
我试过很多次了，直接没问题。 然后你把jdk打进去吧……他们用的人安装个jdk确实太为难了。可以单独打包一个版本
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年5月16日(星期天) 下午2:27 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Waldenth/FuckHamSports] emm (#2) 不用休眠，改一下时间可以直接跑 然后，能不能打包成exe，这样没有java环境的好打开 加休眠是出于对防止服务器端对Get请求的时间进行时钟检测（如果你的开始与结束跑步请求之间间隔的时间很短，而最后的结束请求携带的时间却有几百秒，这样运维方很容易查到异常），我无法保证这样做是否会对账号造成影响。 Java程序的运行必须依赖java环境，即使是exe。如果打包成exe必须在exe中包含jdk，考虑到jdk体积太大，没有进行打包。后续我考虑将其做成开放性Web平台或使用C#进行重构。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
感谢你的建议，我已经更新工程项目，现在可以自我选择是否进行延时模拟；同时，网盘中我更新了打包jre环境，无需安装JDK的项目，使用简单的bat/vbs/exe控制执行，你可以实验一下。

**Comment by Waldenth** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月16日(星期天) 下午4:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Waldenth/FuckHamSports] emm (#2) 我试过很多次了，直接没问题。 然后你把jdk打进去吧……他们用的人安装个jdk确实太为难了。可以单独打包一个版本 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年5月16日(星期天) 下午2:27 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Waldenth/FuckHamSports] emm (#2) 不用休眠，改一下时间可以直接跑 然后，能不能打包成exe，这样没有java环境的好打开 加休眠是出于对防止服务器端对Get请求的时间进行时钟检测（如果你的开始与结束跑步请求之间间隔的时间很短，而最后的结束请求携带的时间却有几百秒，这样运维方很容易查到异常），我无法保证这样做是否会对账号造成影响。 Java程序的运行必须依赖java环境，即使是exe。如果打包成exe必须在exe中包含jdk，考虑到jdk体积太大，没有进行打包。后续我考虑将其做成开放性Web平台或使用C#进行重构。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢你的建议，我已经更新工程项目，现在可以自我选择是否进行延时模拟；同时，网盘中我更新了打包jre环境，无需安装JDK的项目，使用简单的bat/vbs/exe控制执行，你可以实验一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请确认邮件推送是否正常，过多无意义的评论会导致issue closed
