### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by bulesky177** [Waldenth/FuckHamSports#8]
需要其他软件一起吗，我下载了(bug fixed)FuckHamSports-v0.1.5，里面并没有exe应用程序，我该如何使用

**Comment by Waldenth** [comment]
需要JDK-14支持，你可以从[Oracle官网](https://www.oracle.com/java/technologies/javase/jdk14-archive-downloads.html)下载，如果是Windows系统，你可以下载Windows x64 Compressed Archive，解压后添加环境变量即可启动jar文件。如果需要删除JDK环境，移除环境变量后删除解压文件夹即可
