### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by ATRIRobots** [Waldenth/FuckHamSports#9]
在保存配置时报错”导出配置失败“，我需要在何处更改代码

**Comment by Waldenth** [comment]
保存按钮监听方法在`MainFrame.java`中的`saveConfigureButton.addActionListener()`中。
另外，你也可以使用命令行窗口`java -jar <filename>.jar`运行程序，并在保存配置时查看命令行下打印的错误信息定位错误源。

**Comment by ATRIRobots** [comment]
尝试了一下发现保存配置仅在cmd运行时可用
